# Default values for MLflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: mlops-my-test
replicaCount: 3
debug: false

podAnnotations: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80


image:
  repository: ghcr.io/mlflow/mlflow
  tag: v2.11.3
  pullPolicy: IfNotPresent

storage:
  enabled: true
  storageClass: sc-pachyderm
  #size: 10Gi

resources: {}

persistentVolumes:
  datasets:
    name: datasets-pv
    nfsPath: /home/kuser/MLFlow/datasets
    size: 10Gi
  models:
    name: models-pv
    nfsPath: /home/kuser/MLFlow/models
    size: 10Gi
  mlflow:
    name: mlflow-pv
    nfsPath: /home/kuser/MLFlow/mlflow
    size: 10Gi

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: mlflow-experimental
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}

tolerations: []

affinity: {}
