apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv-dev
  namespace: {{ .Release.Namespace }}
  labels:
    type: hostpath
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  #nfs:
  #  path: /ns3vlan123son1gyed/ds8/pachyderm_data_dev
  #  server: sarak.vlan123.son1.gyed.n.telconet.cloud
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /home/kuser/pachyderm/loki  # Specify the directory path on the host
    type: DirectoryOrCreate
