apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv-dev
  namespace: {{ .Release.Namespace }}
  labels:
    type: hostpath
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: {{ .Values.persistentVolumes.mlflow.nfsPath  }}  # Specify the directory path on the host
    type: DirectoryOrCreate
